name: Publish Python 🐍 distribution 📦 to PyPI and TestPyPI

on:
  workflow_dispatch:
  push:
    tags:
    - v*

jobs:
  build:
    name: Build distribution 📦
    runs-on: ubuntu-latest
    environment:
      name: pypi
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.9"
    - name: Install pypa/build
      run: python3 -m pip install --upgrade build twine
    - name: Force setuptools 61.0
      run: pip install setuptools==61.0
    - name: Install dependencies
      run: pip install --upgrade pip && pip install -r requirements.txt
    - name: Perform tests
      run: python3 -m unittest discover tests
    - name: Build a binary wheel and a source tarball
      run: python3 -m build
    - name: Publish to PyPI
    #   env:
    #       TWINE_USERNAME: __token__
    #       TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      uses: pypa/gh-action-pypi-publish@release/v1
